### ISSUE TITLE
v2ray/xray编译不过，不选就能通过

### ISSUE THREAD

**Issue by sherlsenlinmu** [vb1980/Padavan_CI#5]
../transport/internet/websocket/dialer.go:5:2: package embed is not in GOROOT (/opt/hostedtoolcache/go/1.15.15/x64/src/embed)
make[2]: *** [Makefile:30: build_xray] Error 1
make[2]: Leaving directory '/opt/Padavan-KVR/trunk/user/xray'
make[1]: *** [Makefile:248: all] Error 2
make[1]: Leaving directory '/opt/Padavan-KVR/trunk/user'
make: *** [Makefile:202: user_only] Error 2
Error: Process completed with exit code 2.

**Comment by vb1980** [comment]
自己改了源码地址

**Comment by sherlsenlinmu** [comment]
> 自己改了源码地址
试了很多种方法，最后都是卡在xray哪里，
REPOSITORY_URL: https://vb1980:${{ secrets.PRIVREPOTOKEN }}@github.com/vb1980/my-padavan.git
 WORK_PATH: /opt/rt-n56u
这两个不修改，直接卡死在这里

**Comment by sherlsenlinmu** [comment]
Padavan-KVR/trunk/user/xray/Makefile
xray_VERSION := 1.4.2
xray_URL := https://codeload.github.com/xtls/xray-core/tar.gz/v$(xray_VERSION)
这个地址是无效的

**Comment by sherlsenlinmu** [comment]
原：description: 'padavan git branch'
        required: true
        default: 'xray'
现：description: 'padavan git branch'
        required: true
        default: 'main'
原：https://github.com/vb1980/my-padavan.git
现：https://github.com/vb1980/Padavan-KVR.git
