### ISSUE TITLE
Build K2P rainbow kvr from vb1980 private repo提示用户名密码错误

### ISSUE THREAD

**Issue by wokilp** [vb1980/Padavan_CI#7]
大哥，这个用户名密码自动编译的时候提示用户名密码错误，貌似你的所有这个带rainbow的编译都会报错这个，目前测试RM2100和K2P都会报错这个。
![image](https://user-images.githubusercontent.com/66104164/143813603-2fc56be9-a470-4878-92ca-cd226dc90807.png)

**Comment by wokilp** [comment]
![image](https://user-images.githubusercontent.com/66104164/143813903-d33ff013-b645-454f-9bd2-af72f22bc292.png)

**Comment by vb1980** [comment]
rainbow彩虹版私有库，纯粹自己用
